export const colorTokens = {
  primary: '#1677ff',
  success: '#52c41a',
  warning: '#faad14',
  error: '#ff4d4f',
  info: '#1677ff',
  text: '#1f2937',
  textSecondary: '#64748b',
  textTertiary: '#94a3b8',
  textQuaternary: '#cbd5e1',
  label: '#475569',
  border: '#e2e8f0',
  borderLight: '#f1f5f9',
  bgContainer: '#ffffff',
  bgLayout: '#f8fafc',
  bgHover: '#f1f5f9',
} as const;

export const sizeTokens = {
  controlHeight: 36,
  controlHeightSM: 28,
  controlHeightLG: 44,
  controlHeightXS: 24,
  borderRadius: 8,
  borderRadiusXS: 4,
  borderRadiusSM: 6,
  borderRadiusLG: 12,
  fontSize: 14,
  fontSizeSM: 12,
  fontSizeLG: 16,
  fontSizeXL: 20,
  fontSizeHeading1: 32,
  fontSizeHeading2: 24,
  fontSizeHeading3: 20,
  fontSizeHeading4: 16,
  fontSizeHeading5: 14,
  padding: 16,
  paddingSM: 12,
  paddingLG: 24,
  paddingXS: 8,
  paddingXXS: 4,
  margin: 16,
  marginSM: 12,
  marginLG: 24,
  marginXS: 8,
  marginXXS: 4,
} as const;

export const appThemeTokens = {
  colorPrimary: colorTokens.primary,
  colorSuccess: colorTokens.success,
  colorWarning: colorTokens.warning,
  colorError: colorTokens.error,
  colorInfo: colorTokens.info,
  colorText: colorTokens.text,
  colorTextSecondary: colorTokens.textSecondary,
  colorTextTertiary: colorTokens.textTertiary,
  colorTextQuaternary: colorTokens.textQuaternary,
  colorBorder: colorTokens.border,
  colorBorderSecondary: colorTokens.borderLight,
  colorBgContainer: colorTokens.bgContainer,
  colorBgLayout: colorTokens.bgLayout,
  colorBgSpotlight: colorTokens.bgHover,
  borderRadius: sizeTokens.borderRadius,
  borderRadiusSM: sizeTokens.borderRadiusSM,
  borderRadiusLG: sizeTokens.borderRadiusLG,
  borderRadiusXS: sizeTokens.borderRadiusXS,
  controlHeight: sizeTokens.controlHeight,
  controlHeightSM: sizeTokens.controlHeightSM,
  controlHeightLG: sizeTokens.controlHeightLG,
  controlHeightXS: sizeTokens.controlHeightXS,
  fontSize: sizeTokens.fontSize,
  fontSizeSM: sizeTokens.fontSizeSM,
  fontSizeLG: sizeTokens.fontSizeLG,
  fontSizeXL: sizeTokens.fontSizeXL,
  fontSizeHeading1: sizeTokens.fontSizeHeading1,
  fontSizeHeading2: sizeTokens.fontSizeHeading2,
  fontSizeHeading3: sizeTokens.fontSizeHeading3,
  fontSizeHeading4: sizeTokens.fontSizeHeading4,
  fontSizeHeading5: sizeTokens.fontSizeHeading5,
  padding: sizeTokens.padding,
  paddingSM: sizeTokens.paddingSM,
  paddingLG: sizeTokens.paddingLG,
  paddingXS: sizeTokens.paddingXS,
  paddingXXS: sizeTokens.paddingXXS,
  margin: sizeTokens.margin,
  marginSM: sizeTokens.marginSM,
  marginLG: sizeTokens.marginLG,
  marginXS: sizeTokens.marginXS,
  marginXXS: sizeTokens.marginXXS,
} as const;

export const shadowTokens = {
  primary:
    '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
  secondary:
    '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
} as const;

export const motionTokens = {
  fast: '0.1s',
  mid: '0.2s',
  slow: '0.3s',
} as const;
