import { lazy } from 'react';

export const adminModuleRoutes = {
  login: lazy(() => import('./pages/AdminLogin')),
  dashboard: lazy(() => import('./pages/AdminDashboard')),
  news: lazy(() => import('./pages/NewsList')),
  users: lazy(() => import('./pages/UserList')),
  tools: lazy(() => import('./pages/ToolList')),
  appPermissions: lazy(() => import('./pages/AppPermissions')),
  carousel: lazy(() => import('./pages/CarouselList')),
  announcements: lazy(() => import('./pages/AnnouncementList')),
  systemSettings: lazy(() => import('./pages/SystemSettings')),
  platformSettings: lazy(() => import('./pages/PlatformSettings')),
  license: lazy(() => import('./pages/LicenseManagement')),
  security: lazy(() => import('./pages/SecuritySettings')),
  mfaSettings: lazy(() => import('./pages/MfaSettings')),
  notificationServices: lazy(() => import('./pages/NotificationServices')),
  notificationTemplates: lazy(() => import('./pages/NotificationTemplates')),
  thirdPartyNotifications: lazy(() => import('./pages/ThirdPartyNotifications')),
  passwordPolicy: lazy(() => import('./pages/PasswordPolicy')),
  systemUsers: lazy(() => import('./pages/SystemUserList')),
  onlineUsers: lazy(() => import('./pages/OnlineUsers')),
  directories: lazy(() => import('./pages/iam/directories')),
  roles: lazy(() => import('./pages/RoleList')),
  organizations: lazy(() => import('./pages/OrganizationList')),
  businessLogs: lazy(() => import('./pages/BusinessLogs')),
  accessLogs: lazy(() => import('./pages/logs/AccessLogs')),
  aboutUs: lazy(() => import('./pages/AboutUs')),
  logForwarding: lazy(() => import('./pages/LogForwarding')),
  logStorage: lazy(() => import('./pages/LogStorage')),
  aiAudit: lazy(() => import('./pages/logs/AIAudit')),
  aiModels: lazy(() => import('./pages/ai/ModelConfig')),
  aiSecurity: lazy(() => import('./pages/ai/SecurityPolicy')),
  aiSettings: lazy(() => import('./pages/ai/AISettings')),
  aiUsage: lazy(() => import('./pages/ai/ModelUsagePage')),
  knowledgeBase: lazy(() => import('./pages/ai/KnowledgeBase')),
  todos: lazy(() => import('./pages/Todos')),
} as const;
