import { lazy, type ComponentType, type LazyExoticComponent } from 'react';

type ModuleRouteComponent = LazyExoticComponent<ComponentType<any>>;

const adminModuleRouteKeys = [
  'login',
  'dashboard',
  'news',
  'holidayReminders',
  'users',
  'tools',
  'appPermissions',
  'carousel',
  'announcements',
  'systemSettings',
  'platformSettings',
  'operationsManagement',
  'license',
  'security',
  'mfaSettings',
  'notificationServices',
  'notificationTemplates',
  'passwordPolicy',
  'systemUsers',
  'onlineUsers',
  'directories',
  'meetingLocal',
  'meetingSync',
  'roles',
  'organizations',
  'businessLogs',
  'accessLogs',
  'logForwarding',
  'logStorage',
  'aiAudit',
  'aiModels',
  'aiSecurity',
  'aiSettings',
  'aiUsage',
  'knowledgeBase',
  'todos',
] as const;

export type AdminModuleRouteKey = (typeof adminModuleRouteKeys)[number];
export type AdminModuleRoutes = Record<AdminModuleRouteKey, ModuleRouteComponent>;

export const adminModuleRoutes: AdminModuleRoutes = {
  login: lazy(() => import('./pages/AdminLogin')),
  dashboard: lazy(() => import('./pages/AdminDashboard')),
  news: lazy(() => import('./pages/NewsList')),
  holidayReminders: lazy(() => import('./pages/HolidayReminderList')),
  users: lazy(() => import('./pages/UserList')),
  tools: lazy(() => import('./pages/ToolList')),
  appPermissions: lazy(() => import('./pages/AppPermissions')),
  carousel: lazy(() => import('./pages/CarouselList')),
  announcements: lazy(() => import('./pages/AnnouncementList')),
  systemSettings: lazy(() => import('./pages/SystemSettings')),
  platformSettings: lazy(() => import('./pages/PlatformSettings')),
  operationsManagement: lazy(() => import('./pages/OperationsManagement')),
  license: lazy(() => import('./pages/LicenseManagement')),
  security: lazy(() => import('./pages/SecuritySettings')),
  mfaSettings: lazy(() => import('./pages/MfaSettings')),
  notificationServices: lazy(() => import('./pages/NotificationServices')),
  notificationTemplates: lazy(() => import('./pages/NotificationTemplates')),
  passwordPolicy: lazy(() => import('./pages/PasswordPolicy')),
  systemUsers: lazy(() => import('./pages/SystemUserList')),
  onlineUsers: lazy(() => import('./pages/OnlineUsers')),
  directories: lazy(() => import('./pages/iam/directories')),
  meetingLocal: lazy(() => import('./pages/meetings/MeetingLocalManagement')),
  meetingSync: lazy(() => import('./pages/meetings/MeetingThirdPartySync')),
  roles: lazy(() => import('./pages/RoleList')),
  organizations: lazy(() => import('./pages/OrganizationList')),
  businessLogs: lazy(() => import('./pages/BusinessLogs')),
  accessLogs: lazy(() => import('./pages/logs/AccessLogs')),
  logForwarding: lazy(() => import('./pages/LogForwarding')),
  logStorage: lazy(() => import('./pages/LogStorage')),
  aiAudit: lazy(() => import('./pages/logs/AIAudit')),
  aiModels: lazy(() => import('./pages/ai/ModelConfig')),
  aiSecurity: lazy(() => import('./pages/ai/SecurityPolicy')),
  aiSettings: lazy(() => import('./pages/ai/AISettings')),
  aiUsage: lazy(() => import('./pages/ai/ModelUsagePage')),
  knowledgeBase: lazy(() => import('./pages/ai/KnowledgeBase')),
  todos: lazy(() => import('./pages/Todos')),
};
