"""Baseline schema migration from startup inline SQL to Alembic.

Revision ID: 20260305_0001
Revises:
Create Date: 2026-03-05 13:34:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260305_0001"
down_revision = None
branch_labels = None
depends_on = None


BASE_SCHEMA_SQL: tuple[str, ...] = (
    '\nCREATE TABLE IF NOT EXISTS ai_audit_log (\n\tid SERIAL NOT NULL, \n\tevent_id VARCHAR(64), \n\tts TIMESTAMP WITH TIME ZONE, \n\tenv VARCHAR(20), \n\tservice VARCHAR(50), \n\trequest_id VARCHAR(64), \n\ttrace_id VARCHAR(64), \n\tactor_type VARCHAR(20), \n\tactor_id INTEGER, \n\tactor_ip VARCHAR(45), \n\tsession_id VARCHAR(128), \n\tresource_type VARCHAR(50), \n\tresource_id VARCHAR(128), \n\taction VARCHAR(50), \n\tprovider VARCHAR(50), \n\tmodel VARCHAR(100), \n\tapi_key_fingerprint VARCHAR(16), \n\tinput_policy_result VARCHAR(20), \n\toutput_policy_result VARCHAR(20), \n\tpolicy_hits TEXT, \n\tlatency_ms INTEGER, \n\ttokens_in INTEGER, \n\ttokens_out INTEGER, \n\tstatus VARCHAR(20), \n\terror_code VARCHAR(50), \n\terror_reason TEXT, \n\tprompt_hash VARCHAR(64), \n\toutput_hash VARCHAR(64), \n\tmeta_info JSON, \n\tprompt_preview VARCHAR(200), \n\tsource VARCHAR(20), \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS ai_model_quotas (\n\tid SERIAL NOT NULL, \n\tmodel_name VARCHAR, \n\tdaily_token_limit INTEGER, \n\tdaily_request_limit INTEGER, \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS ai_providers (\n\tid SERIAL NOT NULL, \n\tname VARCHAR, \n\ttype VARCHAR, \n\tmodel_kind VARCHAR, \n\tbase_url VARCHAR, \n\tapi_key VARCHAR, \n\tmodel VARCHAR, \n\tis_active BOOLEAN, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS ai_security_policies (\n\tid SERIAL NOT NULL, \n\tname VARCHAR, \n\ttype VARCHAR, \n\tcontent TEXT, \n\taction VARCHAR, \n\tis_enabled BOOLEAN, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS announcements (\n\tid SERIAL NOT NULL, \n\ttag VARCHAR, \n\ttitle VARCHAR, \n\tcontent TEXT, \n\ttime VARCHAR, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tcolor VARCHAR, \n\tis_urgent BOOLEAN, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS business_logs (\n\tid SERIAL NOT NULL, \n\toperator VARCHAR, \n\taction VARCHAR, \n\ttarget VARCHAR, \n\tip_address VARCHAR, \n\tstatus VARCHAR, \n\tdetail TEXT, \n\ttrace_id VARCHAR, \n\tsource VARCHAR, \n\tdomain VARCHAR, \n\ttimestamp VARCHAR, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS carousel_items (\n\tid SERIAL NOT NULL, \n\ttitle VARCHAR, \n\timage VARCHAR, \n\turl VARCHAR, \n\tbadge VARCHAR, \n\tsort_order INTEGER, \n\tis_active BOOLEAN, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS departments (\n\tid SERIAL NOT NULL, \n\tname VARCHAR, \n\tparent_id INTEGER, \n\tmanager VARCHAR, \n\tdescription VARCHAR, \n\tsort_order INTEGER, \n\tdirectory_id INTEGER, \n\texternal_id VARCHAR(255), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(parent_id) REFERENCES departments (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS directory_configs (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(128) NOT NULL, \n\ttype VARCHAR(20) NOT NULL, \n\thost VARCHAR(255) NOT NULL, \n\tport INTEGER NOT NULL, \n\tuse_ssl BOOLEAN NOT NULL, \n\tstart_tls BOOLEAN NOT NULL, \n\tbind_dn VARCHAR(512), \n\tremark VARCHAR(500), \n\tbind_password_ciphertext TEXT, \n\tbase_dn VARCHAR(512) NOT NULL, \n\tuser_filter VARCHAR(512) NOT NULL, \n\tusername_attr VARCHAR(128) NOT NULL, \n\temail_attr VARCHAR(128) NOT NULL, \n\tdisplay_name_attr VARCHAR(128) NOT NULL, \n\tmobile_attr VARCHAR(128) NOT NULL, \n\tavatar_attr VARCHAR(128) NOT NULL, \n\tsync_mode VARCHAR(20) NOT NULL, \n\tsync_interval_minutes INTEGER, \n\tsync_page_size INTEGER NOT NULL, \n\tsync_cursor VARCHAR(255), \n\torg_base_dn VARCHAR(512), \n\torg_filter VARCHAR(512), \n\torg_name_attr VARCHAR(128), \n\tgroup_base_dn VARCHAR(512), \n\tgroup_filter VARCHAR(512), \n\tgroup_name_attr VARCHAR(128), \n\tgroup_desc_attr VARCHAR(128), \n\tdelete_grace_days INTEGER NOT NULL, \n\tdelete_whitelist TEXT, \n\tenabled BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS kb_query_logs (\n\tid SERIAL NOT NULL, \n\tquery TEXT, \n\ttop_score FLOAT, \n\thit_level VARCHAR(10), \n\thit_doc_ids TEXT, \n\tcalled_llm BOOLEAN, \n\ttrace_id VARCHAR(64), \n\tuser_id INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS license_state (\n\tid INTEGER NOT NULL, \n\tproduct_id VARCHAR(128) NOT NULL, \n\tinstallation_id VARCHAR(128) NOT NULL, \n\tgrant_type VARCHAR(20) NOT NULL, \n\tcustomer VARCHAR(255), \n\tfeatures JSON NOT NULL, \n\tlimits JSON NOT NULL, \n\tpayload JSON, \n\tnot_before TIMESTAMP WITH TIME ZONE NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsignature TEXT NOT NULL, \n\tfingerprint VARCHAR(128) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\treason VARCHAR(255), \n\tlast_seen_time TIMESTAMP WITH TIME ZONE, \n\tinstalled_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS log_forwarding_config (\n\tid SERIAL NOT NULL, \n\ttype VARCHAR, \n\tendpoint VARCHAR, \n\tport INTEGER, \n\tsecret_token VARCHAR, \n\tenabled BOOLEAN, \n\tlog_types VARCHAR, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS news (\n\tid SERIAL NOT NULL, \n\ttitle VARCHAR, \n\tsummary TEXT, \n\tcategory VARCHAR, \n\tdate DATE, \n\tauthor VARCHAR, \n\timage VARCHAR, \n\tis_top BOOLEAN, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS permissions (\n\tid SERIAL NOT NULL, \n\tapp_id VARCHAR(50), \n\tcode VARCHAR, \n\tdescription VARCHAR, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_perm_app_code UNIQUE (app_id, code)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS roles (\n\tid SERIAL NOT NULL, \n\tapp_id VARCHAR(50), \n\tcode VARCHAR, \n\tname VARCHAR, \n\tdescription VARCHAR, \n\tlimit_scope BOOLEAN, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tdirectory_id INTEGER, \n\texternal_id VARCHAR(255), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_role_app_code UNIQUE (app_id, code)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS system_config (\n\tkey VARCHAR NOT NULL, \n\tvalue VARCHAR, \n\tPRIMARY KEY (key)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS system_logs (\n\tid SERIAL NOT NULL, \n\tlevel VARCHAR, \n\tmodule VARCHAR, \n\tmessage TEXT, \n\ttimestamp VARCHAR, \n\tip_address VARCHAR, \n\trequest_path VARCHAR, \n\tmethod VARCHAR, \n\tstatus_code INTEGER, \n\tresponse_time FLOAT, \n\trequest_size INTEGER, \n\tuser_agent VARCHAR, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS tools (\n\tid SERIAL NOT NULL, \n\tname VARCHAR, \n\ticon_name VARCHAR, \n\turl VARCHAR, \n\tcolor VARCHAR, \n\tcategory VARCHAR, \n\tdescription VARCHAR, \n\timage VARCHAR, \n\tsort_order INTEGER, \n\tvisible_to_departments TEXT, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS users (\n\tid SERIAL NOT NULL, \n\tusername VARCHAR, \n\temail VARCHAR, \n\thashed_password VARCHAR, \n\taccount_type VARCHAR(20) NOT NULL, \n\tis_active BOOLEAN, \n\tfailed_attempts INTEGER, \n\tlocked_until TIMESTAMP WITH TIME ZONE, \n\tname VARCHAR, \n\tavatar VARCHAR, \n\tdirectory_id INTEGER, \n\texternal_id VARCHAR(255), \n\tpending_delete_at TIMESTAMP WITH TIME ZONE, \n\tpassword_violates_policy BOOLEAN, \n\tpassword_change_required BOOLEAN, \n\tpassword_changed_at TIMESTAMP WITH TIME ZONE, \n\tauth_source VARCHAR(50) NOT NULL, \n\ttotp_secret VARCHAR(255), \n\ttotp_enabled BOOLEAN NOT NULL, \n\temail_mfa_enabled BOOLEAN NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS announcement_reads (\n\tid SERIAL NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tannouncement_id INTEGER NOT NULL, \n\tread_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_announcement_read_user_announcement UNIQUE (user_id, announcement_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(announcement_id) REFERENCES announcements (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS employees (\n\tid SERIAL NOT NULL, \n\taccount VARCHAR, \n\tjob_number VARCHAR, \n\tname VARCHAR, \n\tgender VARCHAR, \n\tdepartment VARCHAR, \n\tprimary_department_id INTEGER, \n\trole VARCHAR, \n\temail VARCHAR, \n\tphone VARCHAR, \n\tlocation VARCHAR, \n\tavatar VARCHAR, \n\tavatar_hash VARCHAR(64), \n\tstatus VARCHAR, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(primary_department_id) REFERENCES departments (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS file_metadata (\n\tid SERIAL NOT NULL, \n\toriginal_name VARCHAR, \n\tstored_name VARCHAR, \n\tbucket VARCHAR, \n\tsize INTEGER, \n\tcontent_type VARCHAR, \n\tuploader_id INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(uploader_id) REFERENCES users (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS kb_documents (\n\tid SERIAL NOT NULL, \n\ttitle VARCHAR, \n\tsource_type VARCHAR(20), \n\tcontent TEXT, \n\ttags TEXT, \n\tapp_id VARCHAR(50), \n\tacl TEXT, \n\tstatus VARCHAR(20), \n\tchunk_count INTEGER, \n\tcreated_by INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(created_by) REFERENCES users (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS license_events (\n\tid SERIAL NOT NULL, \n\tevent_type VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\treason VARCHAR(128), \n\tpayload JSON, \n\tsignature TEXT, \n\tfingerprint VARCHAR(128), \n\tproduct_id VARCHAR(128), \n\tinstallation_id VARCHAR(128), \n\tgrant_type VARCHAR(20), \n\tcustomer VARCHAR(255), \n\tactor_id INTEGER, \n\tactor_username VARCHAR(255), \n\tip_address VARCHAR(64), \n\ttrace_id VARCHAR(128), \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS notifications (\n\tid SERIAL NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tmessage TEXT NOT NULL, \n\ttype VARCHAR(20) NOT NULL, \n\taction_url VARCHAR, \n\tcreated_by INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(created_by) REFERENCES users (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS role_permissions (\n\trole_id INTEGER NOT NULL, \n\tpermission_id INTEGER NOT NULL, \n\tPRIMARY KEY (role_id, permission_id), \n\tFOREIGN KEY(role_id) REFERENCES roles (id), \n\tFOREIGN KEY(permission_id) REFERENCES permissions (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS sync_jobs (\n\tid SERIAL NOT NULL, \n\tdirectory_id INTEGER NOT NULL, \n\tjob_type VARCHAR(20) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tstage VARCHAR(20), \n\tcheckpoint_data JSON, \n\tstats JSON, \n\tcursor_start VARCHAR(255), \n\tcursor_end VARCHAR(255), \n\tmax_usn_seen VARCHAR(255), \n\terror_detail TEXT, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(directory_id) REFERENCES directory_configs (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS todos (\n\tid SERIAL NOT NULL, \n\ttitle VARCHAR, \n\tdescription TEXT, \n\tstatus VARCHAR, \n\tpriority INTEGER, \n\tdue_at TIMESTAMP WITH TIME ZONE, \n\tcreator_id INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(creator_id) REFERENCES users (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS user_password_history (\n\tid SERIAL NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\thashed_password VARCHAR NOT NULL, \n\tchanged_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS user_roles (\n\tuser_id INTEGER NOT NULL, \n\trole_id INTEGER NOT NULL, \n\tPRIMARY KEY (user_id, role_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(role_id) REFERENCES roles (id)\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS webauthn_credentials (\n\tid SERIAL NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tcredential_id TEXT NOT NULL, \n\tpublic_key TEXT NOT NULL, \n\tsign_count INTEGER NOT NULL, \n\tname VARCHAR(128) NOT NULL, \n\ttransports TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS kb_chunks (\n\tid SERIAL NOT NULL, \n\tdoc_id INTEGER, \n\tsection VARCHAR, \n\tcontent TEXT, \n\tchunk_index INTEGER, \n\tembedding VECTOR(768), \n\tcreated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(doc_id) REFERENCES kb_documents (id) ON DELETE CASCADE\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS notification_receipts (\n\tid SERIAL NOT NULL, \n\tnotification_id INTEGER NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tis_read BOOLEAN NOT NULL, \n\tread_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_notification_receipt_notification_user UNIQUE (notification_id, user_id), \n\tFOREIGN KEY(notification_id) REFERENCES notifications (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS todo_dept_assignees (\n\ttodo_id INTEGER NOT NULL, \n\tdepartment_id INTEGER NOT NULL, \n\tPRIMARY KEY (todo_id, department_id), \n\tFOREIGN KEY(todo_id) REFERENCES todos (id) ON DELETE CASCADE, \n\tFOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE CASCADE\n)\n\n',
    '\nCREATE TABLE IF NOT EXISTS todo_user_assignees (\n\ttodo_id INTEGER NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tPRIMARY KEY (todo_id, user_id), \n\tFOREIGN KEY(todo_id) REFERENCES todos (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)\n\n',
    'CREATE INDEX IF NOT EXISTS ix_ai_audit_log_actor_id ON ai_audit_log (actor_id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_ai_audit_log_event_id ON ai_audit_log (event_id)',
    'CREATE INDEX IF NOT EXISTS ix_ai_audit_log_id ON ai_audit_log (id)',
    'CREATE INDEX IF NOT EXISTS ix_ai_audit_log_provider ON ai_audit_log (provider)',
    'CREATE INDEX IF NOT EXISTS ix_ai_audit_log_status ON ai_audit_log (status)',
    'CREATE INDEX IF NOT EXISTS ix_ai_audit_log_trace_id ON ai_audit_log (trace_id)',
    'CREATE INDEX IF NOT EXISTS ix_ai_audit_log_ts ON ai_audit_log (ts)',
    'CREATE INDEX IF NOT EXISTS ix_ai_model_quotas_id ON ai_model_quotas (id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_ai_model_quotas_model_name ON ai_model_quotas (model_name)',
    'CREATE INDEX IF NOT EXISTS ix_ai_providers_id ON ai_providers (id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_ai_providers_name ON ai_providers (name)',
    'CREATE INDEX IF NOT EXISTS ix_ai_security_policies_id ON ai_security_policies (id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_ai_security_policies_name ON ai_security_policies (name)',
    'CREATE INDEX IF NOT EXISTS ix_announcements_created_at ON announcements (created_at)',
    'CREATE INDEX IF NOT EXISTS ix_announcements_id ON announcements (id)',
    'CREATE INDEX IF NOT EXISTS ix_business_logs_action ON business_logs (action)',
    'CREATE INDEX IF NOT EXISTS ix_business_logs_domain ON business_logs (domain)',
    'CREATE INDEX IF NOT EXISTS ix_business_logs_id ON business_logs (id)',
    'CREATE INDEX IF NOT EXISTS ix_business_logs_operator ON business_logs (operator)',
    'CREATE INDEX IF NOT EXISTS ix_business_logs_trace_id ON business_logs (trace_id)',
    'CREATE INDEX IF NOT EXISTS ix_carousel_items_id ON carousel_items (id)',
    'CREATE INDEX IF NOT EXISTS ix_departments_directory_id ON departments (directory_id)',
    'CREATE INDEX IF NOT EXISTS ix_departments_external_id ON departments (external_id)',
    'CREATE INDEX IF NOT EXISTS ix_departments_id ON departments (id)',
    'CREATE INDEX IF NOT EXISTS ix_departments_name ON departments (name)',
    'CREATE INDEX IF NOT EXISTS ix_directory_configs_enabled ON directory_configs (enabled)',
    'CREATE INDEX IF NOT EXISTS ix_directory_configs_id ON directory_configs (id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_directory_configs_name ON directory_configs (name)',
    'CREATE INDEX IF NOT EXISTS ix_directory_configs_type ON directory_configs (type)',
    'CREATE INDEX IF NOT EXISTS ix_kb_query_logs_id ON kb_query_logs (id)',
    'CREATE INDEX IF NOT EXISTS ix_kb_query_logs_trace_id ON kb_query_logs (trace_id)',
    'CREATE INDEX IF NOT EXISTS ix_kb_query_logs_user_id ON kb_query_logs (user_id)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_expires_at ON license_state (expires_at)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_fingerprint ON license_state (fingerprint)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_id ON license_state (id)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_installation_id ON license_state (installation_id)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_last_seen_time ON license_state (last_seen_time)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_product_id ON license_state (product_id)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_status ON license_state (status)',
    'CREATE INDEX IF NOT EXISTS ix_log_forwarding_config_id ON log_forwarding_config (id)',
    'CREATE INDEX IF NOT EXISTS ix_news_id ON news (id)',
    'CREATE INDEX IF NOT EXISTS ix_news_title ON news (title)',
    'CREATE INDEX IF NOT EXISTS ix_permissions_app_id ON permissions (app_id)',
    'CREATE INDEX IF NOT EXISTS ix_permissions_code ON permissions (code)',
    'CREATE INDEX IF NOT EXISTS ix_permissions_id ON permissions (id)',
    'CREATE INDEX IF NOT EXISTS ix_roles_app_id ON roles (app_id)',
    'CREATE INDEX IF NOT EXISTS ix_roles_code ON roles (code)',
    'CREATE INDEX IF NOT EXISTS ix_roles_directory_id ON roles (directory_id)',
    'CREATE INDEX IF NOT EXISTS ix_roles_external_id ON roles (external_id)',
    'CREATE INDEX IF NOT EXISTS ix_roles_id ON roles (id)',
    'CREATE INDEX IF NOT EXISTS ix_system_config_key ON system_config (key)',
    'CREATE INDEX IF NOT EXISTS ix_system_logs_id ON system_logs (id)',
    'CREATE INDEX IF NOT EXISTS ix_system_logs_level ON system_logs (level)',
    'CREATE INDEX IF NOT EXISTS ix_system_logs_module ON system_logs (module)',
    'CREATE INDEX IF NOT EXISTS ix_tools_id ON tools (id)',
    'CREATE INDEX IF NOT EXISTS ix_tools_name ON tools (name)',
    'CREATE INDEX IF NOT EXISTS ix_users_account_type ON users (account_type)',
    'CREATE INDEX IF NOT EXISTS ix_users_auth_source ON users (auth_source)',
    'CREATE INDEX IF NOT EXISTS ix_users_directory_id ON users (directory_id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)',
    'CREATE INDEX IF NOT EXISTS ix_users_external_id ON users (external_id)',
    'CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username)',
    'CREATE INDEX IF NOT EXISTS ix_announcement_reads_announcement_id ON announcement_reads (announcement_id)',
    'CREATE INDEX IF NOT EXISTS ix_announcement_reads_id ON announcement_reads (id)',
    'CREATE INDEX IF NOT EXISTS ix_announcement_reads_read_at ON announcement_reads (read_at)',
    'CREATE INDEX IF NOT EXISTS ix_announcement_reads_user_id ON announcement_reads (user_id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_employees_account ON employees (account)',
    'CREATE INDEX IF NOT EXISTS ix_employees_avatar_hash ON employees (avatar_hash)',
    'CREATE INDEX IF NOT EXISTS ix_employees_department ON employees (department)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_employees_email ON employees (email)',
    'CREATE INDEX IF NOT EXISTS ix_employees_id ON employees (id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_employees_job_number ON employees (job_number)',
    'CREATE INDEX IF NOT EXISTS ix_employees_name ON employees (name)',
    'CREATE INDEX IF NOT EXISTS ix_employees_primary_department_id ON employees (primary_department_id)',
    'CREATE INDEX IF NOT EXISTS ix_file_metadata_created_at ON file_metadata (created_at)',
    'CREATE INDEX IF NOT EXISTS ix_file_metadata_id ON file_metadata (id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_file_metadata_stored_name ON file_metadata (stored_name)',
    'CREATE INDEX IF NOT EXISTS ix_kb_documents_app_id ON kb_documents (app_id)',
    'CREATE INDEX IF NOT EXISTS ix_kb_documents_id ON kb_documents (id)',
    'CREATE INDEX IF NOT EXISTS ix_kb_documents_status ON kb_documents (status)',
    'CREATE INDEX IF NOT EXISTS ix_kb_documents_title ON kb_documents (title)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_actor_id ON license_events (actor_id)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_created_at ON license_events (created_at)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_event_type ON license_events (event_type)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_id ON license_events (id)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_installation_id ON license_events (installation_id)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_product_id ON license_events (product_id)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_reason ON license_events (reason)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_status ON license_events (status)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_trace_id ON license_events (trace_id)',
    'CREATE INDEX IF NOT EXISTS ix_notifications_created_at ON notifications (created_at)',
    'CREATE INDEX IF NOT EXISTS ix_notifications_created_by ON notifications (created_by)',
    'CREATE INDEX IF NOT EXISTS ix_notifications_id ON notifications (id)',
    'CREATE INDEX IF NOT EXISTS ix_sync_jobs_directory_id ON sync_jobs (directory_id)',
    'CREATE INDEX IF NOT EXISTS ix_sync_jobs_id ON sync_jobs (id)',
    'CREATE INDEX IF NOT EXISTS ix_sync_jobs_status ON sync_jobs (status)',
    'CREATE INDEX IF NOT EXISTS ix_todos_id ON todos (id)',
    'CREATE INDEX IF NOT EXISTS ix_todos_status ON todos (status)',
    'CREATE INDEX IF NOT EXISTS ix_todos_title ON todos (title)',
    'CREATE INDEX IF NOT EXISTS ix_user_password_history_changed_at ON user_password_history (changed_at)',
    'CREATE INDEX IF NOT EXISTS ix_user_password_history_id ON user_password_history (id)',
    'CREATE INDEX IF NOT EXISTS ix_user_password_history_user_id ON user_password_history (user_id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_webauthn_credentials_credential_id ON webauthn_credentials (credential_id)',
    'CREATE INDEX IF NOT EXISTS ix_webauthn_credentials_id ON webauthn_credentials (id)',
    'CREATE INDEX IF NOT EXISTS ix_webauthn_credentials_user_id ON webauthn_credentials (user_id)',
    'CREATE INDEX IF NOT EXISTS ix_kb_chunks_doc_id ON kb_chunks (doc_id)',
    'CREATE INDEX IF NOT EXISTS ix_kb_chunks_id ON kb_chunks (id)',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_created_at ON notification_receipts (created_at)',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_id ON notification_receipts (id)',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_is_read ON notification_receipts (is_read)',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_notification_id ON notification_receipts (notification_id)',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_read_at ON notification_receipts (read_at)',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_user_id ON notification_receipts (user_id)',
)


LEGACY_STARTUP_SQL: tuple[str, ...] = (
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS account_type VARCHAR(20) DEFAULT 'PORTAL'",
    "UPDATE users SET account_type = 'PORTAL' WHERE account_type IS NULL OR account_type = ''",
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS password_violates_policy BOOLEAN DEFAULT FALSE',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS password_change_required BOOLEAN DEFAULT FALSE',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ DEFAULT NOW()',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS directory_id INTEGER',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS external_id VARCHAR(255)',
    'UPDATE users SET password_changed_at = NOW() WHERE password_changed_at IS NULL',
    'UPDATE users SET password_change_required = FALSE WHERE password_change_required IS NULL',
    "UPDATE users SET account_type = 'SYSTEM' WHERE username = 'admin'",
    'CREATE INDEX IF NOT EXISTS ix_users_account_type ON users (account_type)',
    'CREATE INDEX IF NOT EXISTS ix_users_password_changed_at ON users (password_changed_at)',
    'CREATE INDEX IF NOT EXISTS ix_users_directory_id ON users (directory_id)',
    'CREATE INDEX IF NOT EXISTS ix_users_external_id ON users (external_id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_users_directory_external_id ON users (directory_id, external_id) WHERE external_id IS NOT NULL',
    'CREATE TABLE IF NOT EXISTS user_password_history (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), hashed_password VARCHAR NOT NULL, changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW())',
    'CREATE INDEX IF NOT EXISTS ix_user_password_history_user_id_changed_at ON user_password_history (user_id, changed_at DESC)',
    'ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()',
    'UPDATE announcements SET created_at = NOW() WHERE created_at IS NULL',
    'CREATE INDEX IF NOT EXISTS ix_announcements_created_at ON announcements (created_at DESC)',
    'CREATE TABLE IF NOT EXISTS announcement_reads (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), announcement_id INTEGER NOT NULL REFERENCES announcements(id), read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT uq_announcement_read_user_announcement UNIQUE (user_id, announcement_id))',
    'CREATE INDEX IF NOT EXISTS ix_announcement_reads_user_announcement ON announcement_reads (user_id, announcement_id)',
    "CREATE TABLE IF NOT EXISTS notifications (id SERIAL PRIMARY KEY, title VARCHAR NOT NULL, message TEXT NOT NULL, type VARCHAR(20) NOT NULL DEFAULT 'info', action_url VARCHAR, created_by INTEGER REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())",
    'CREATE INDEX IF NOT EXISTS ix_notifications_created_at ON notifications (created_at DESC)',
    'CREATE INDEX IF NOT EXISTS ix_notifications_created_by ON notifications (created_by)',
    'CREATE TABLE IF NOT EXISTS notification_receipts (id SERIAL PRIMARY KEY, notification_id INTEGER NOT NULL REFERENCES notifications(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, is_read BOOLEAN NOT NULL DEFAULT FALSE, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT uq_notification_receipt_notification_user UNIQUE (notification_id, user_id))',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_user_read_created_at ON notification_receipts (user_id, is_read, created_at DESC)',
    'CREATE INDEX IF NOT EXISTS ix_notification_receipts_notification_id ON notification_receipts (notification_id)',
    "CREATE TABLE IF NOT EXISTS directory_configs (id SERIAL PRIMARY KEY, name VARCHAR(128) NOT NULL UNIQUE, type VARCHAR(20) NOT NULL, host VARCHAR(255) NOT NULL, port INTEGER NOT NULL DEFAULT 389, use_ssl BOOLEAN NOT NULL DEFAULT FALSE, start_tls BOOLEAN NOT NULL DEFAULT FALSE, bind_dn VARCHAR(512), remark VARCHAR(500), bind_password_ciphertext TEXT, base_dn VARCHAR(512) NOT NULL, user_filter VARCHAR(512) NOT NULL DEFAULT '(&(objectClass=inetOrgPerson)(uid={username}))', username_attr VARCHAR(128) NOT NULL DEFAULT 'uid', email_attr VARCHAR(128) NOT NULL DEFAULT 'mail', display_name_attr VARCHAR(128) NOT NULL DEFAULT 'cn', mobile_attr VARCHAR(128) NOT NULL DEFAULT 'mobile', avatar_attr VARCHAR(128) NOT NULL DEFAULT 'jpegPhoto', sync_mode VARCHAR(20) NOT NULL DEFAULT 'manual', sync_interval_minutes INTEGER, enabled BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())",
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS remark VARCHAR(500)',
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS sync_mode VARCHAR(20) NOT NULL DEFAULT 'manual'",
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS sync_interval_minutes INTEGER',
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS mobile_attr VARCHAR(128) NOT NULL DEFAULT 'mobile'",
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS avatar_attr VARCHAR(128) NOT NULL DEFAULT 'jpegPhoto'",
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS sync_page_size INTEGER NOT NULL DEFAULT 1000',
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS sync_cursor VARCHAR(255)',
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS org_base_dn VARCHAR(512)',
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS org_filter VARCHAR(512) DEFAULT '(objectClass=organizationalUnit)'",
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS org_name_attr VARCHAR(128) DEFAULT 'ou'",
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS group_base_dn VARCHAR(512)',
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS group_filter VARCHAR(512) DEFAULT '(objectClass=groupOfNames)'",
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS group_name_attr VARCHAR(128) DEFAULT 'cn'",
    "ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS group_desc_attr VARCHAR(128) DEFAULT 'description'",
    "ALTER TABLE directory_configs ALTER COLUMN user_filter SET DEFAULT '(&(objectClass=inetOrgPerson)(uid={username}))'",
    "ALTER TABLE directory_configs ALTER COLUMN username_attr SET DEFAULT 'uid'",
    "ALTER TABLE directory_configs ALTER COLUMN display_name_attr SET DEFAULT 'cn'",
    "ALTER TABLE directory_configs ALTER COLUMN avatar_attr SET DEFAULT 'jpegPhoto'",
    'CREATE INDEX IF NOT EXISTS ix_directory_configs_enabled ON directory_configs (enabled)',
    'CREATE INDEX IF NOT EXISTS ix_directory_configs_type ON directory_configs (type)',
    'CREATE INDEX IF NOT EXISTS ix_directory_configs_sync_mode ON directory_configs (sync_mode)',
    'ALTER TABLE departments ADD COLUMN IF NOT EXISTS directory_id INTEGER',
    'ALTER TABLE departments ADD COLUMN IF NOT EXISTS external_id VARCHAR(255)',
    'CREATE INDEX IF NOT EXISTS ix_departments_directory_id ON departments (directory_id)',
    'CREATE INDEX IF NOT EXISTS ix_departments_external_id ON departments (external_id)',
    'ALTER TABLE roles ADD COLUMN IF NOT EXISTS directory_id INTEGER',
    'ALTER TABLE roles ADD COLUMN IF NOT EXISTS external_id VARCHAR(255)',
    'CREATE INDEX IF NOT EXISTS ix_roles_directory_id ON roles (directory_id)',
    'CREATE INDEX IF NOT EXISTS ix_roles_external_id ON roles (external_id)',
    "CREATE TABLE IF NOT EXISTS license_state (id INTEGER PRIMARY KEY, product_id VARCHAR(128) NOT NULL, installation_id VARCHAR(128) NOT NULL, grant_type VARCHAR(20) NOT NULL, customer VARCHAR(255), features JSONB NOT NULL DEFAULT '{}'::jsonb, limits JSONB NOT NULL DEFAULT '{}'::jsonb, payload JSONB, not_before TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, signature TEXT NOT NULL, fingerprint VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', reason VARCHAR(255), last_seen_time TIMESTAMPTZ, installed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())",
    'CREATE INDEX IF NOT EXISTS ix_license_state_status ON license_state (status)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_expires_at ON license_state (expires_at)',
    'CREATE INDEX IF NOT EXISTS ix_license_state_installation_id ON license_state (installation_id)',
    'CREATE TABLE IF NOT EXISTS license_events (id SERIAL PRIMARY KEY, event_type VARCHAR(64) NOT NULL, status VARCHAR(20) NOT NULL, reason VARCHAR(128), payload JSONB, signature TEXT, fingerprint VARCHAR(128), product_id VARCHAR(128), installation_id VARCHAR(128), grant_type VARCHAR(20), customer VARCHAR(255), actor_id INTEGER REFERENCES users(id), actor_username VARCHAR(255), ip_address VARCHAR(64), trace_id VARCHAR(128), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())',
    'CREATE INDEX IF NOT EXISTS ix_license_events_type_created_at ON license_events (event_type, created_at DESC)',
    'CREATE INDEX IF NOT EXISTS ix_license_events_status_created_at ON license_events (status, created_at DESC)',
    "ALTER TABLE ai_providers ADD COLUMN IF NOT EXISTS model_kind VARCHAR DEFAULT 'text'",
    "UPDATE ai_providers SET model_kind = 'text' WHERE model_kind IS NULL OR model_kind = ''",
    'ALTER TABLE roles ADD COLUMN IF NOT EXISTS description VARCHAR',
    'ALTER TABLE kb_documents ADD COLUMN IF NOT EXISTS content TEXT',
    'CREATE INDEX IF NOT EXISTS ix_kb_chunks_doc_id_chunk_index ON kb_chunks (doc_id, chunk_index)',
    'CREATE INDEX IF NOT EXISTS ix_kb_documents_status_id ON kb_documents (status, id)',
    'CREATE INDEX IF NOT EXISTS ix_kb_chunks_embedding_ivfflat ON kb_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)',
    'ANALYZE kb_chunks',
    "INSERT INTO system_config (key, value) VALUES ('max_concurrent_sessions', '0') ON CONFLICT (key) DO NOTHING",
    "INSERT INTO system_config (key, value) VALUES ('login_session_timeout_minutes', '5') ON CONFLICT (key) DO NOTHING",
    "INSERT INTO system_config (key, value) VALUES ('login_session_absolute_timeout_minutes', '480') ON CONFLICT (key) DO NOTHING",
    "INSERT INTO system_config (key, value) VALUES ('login_session_refresh_window_minutes', '10') ON CONFLICT (key) DO NOTHING",
    "INSERT INTO system_config (key, value) VALUES ('login_captcha_threshold', '3') ON CONFLICT (key) DO NOTHING",
    "INSERT INTO system_config (key, value) VALUES ('security_lockout_scope', 'account') ON CONFLICT (key) DO NOTHING",
    "INSERT INTO system_config (key, value) VALUES ('security_force_change_password_after_reset', 'false') ON CONFLICT (key) DO NOTHING",
    "CREATE TABLE IF NOT EXISTS sync_jobs (id SERIAL PRIMARY KEY, directory_id INTEGER NOT NULL REFERENCES directory_configs(id), job_type VARCHAR(20) NOT NULL DEFAULT 'full', status VARCHAR(20) NOT NULL DEFAULT 'running', stage VARCHAR(20), checkpoint_data JSONB, stats JSONB, cursor_start VARCHAR(255), cursor_end VARCHAR(255), max_usn_seen VARCHAR(255), error_detail TEXT, started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), finished_at TIMESTAMPTZ)",
    'CREATE INDEX IF NOT EXISTS ix_sync_jobs_directory_id ON sync_jobs (directory_id)',
    'CREATE INDEX IF NOT EXISTS ix_sync_jobs_status ON sync_jobs (status)',
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS delete_grace_days INTEGER NOT NULL DEFAULT 7',
    'ALTER TABLE directory_configs ADD COLUMN IF NOT EXISTS delete_whitelist TEXT',
    'ALTER TABLE employees ADD COLUMN IF NOT EXISTS primary_department_id INTEGER REFERENCES departments(id)',
    'ALTER TABLE employees ADD COLUMN IF NOT EXISTS avatar_hash VARCHAR(64)',
    'CREATE INDEX IF NOT EXISTS ix_employees_primary_department_id ON employees (primary_department_id)',
    'CREATE INDEX IF NOT EXISTS ix_employees_avatar_hash ON employees (avatar_hash)',
    'ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_delete_at TIMESTAMP WITH TIME ZONE;',
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_source VARCHAR(50) NOT NULL DEFAULT 'local';",
    "\n            UPDATE users \n            SET auth_source = CASE \n                WHEN dc.type = 'ad' THEN 'ad'\n                ELSE 'ldap'\n            END\n            FROM directory_configs dc\n            WHERE users.directory_id = dc.id AND users.directory_id IS NOT NULL AND users.auth_source = 'local';\n        ",
    'ALTER TABLE employees DROP COLUMN IF EXISTS source;',
    '\n            ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(255);\n        ',
    '\n            ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled BOOLEAN NOT NULL DEFAULT FALSE;\n        ',
    '\n            ALTER TABLE users ADD COLUMN IF NOT EXISTS email_mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;\n        ',
    "\n            CREATE TABLE IF NOT EXISTS webauthn_credentials (\n                id SERIAL PRIMARY KEY,\n                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n                credential_id TEXT NOT NULL UNIQUE,\n                public_key TEXT NOT NULL,\n                sign_count INTEGER NOT NULL DEFAULT 0,\n                name VARCHAR(128) NOT NULL DEFAULT 'Security Key',\n                transports TEXT,\n                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n            )\n        ",
    'CREATE INDEX IF NOT EXISTS ix_webauthn_credentials_user_id ON webauthn_credentials (user_id)',
    'CREATE UNIQUE INDEX IF NOT EXISTS ix_webauthn_credentials_credential_id ON webauthn_credentials (credential_id)',
)


def upgrade() -> None:
    # pgvector type is required by kb_chunks.embedding vector column.
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))

    for statement in BASE_SCHEMA_SQL:
        op.execute(sa.text(statement))

    # One-time carry-over from historical startup migrations.
    for statement in LEGACY_STARTUP_SQL:
        op.execute(sa.text(statement))


def downgrade() -> None:
    raise NotImplementedError(
        "Baseline migration downgrade is intentionally disabled to avoid destructive data loss."
    )
